version: '3'

services:

  postgres:
    container_name:  postgres
    image:           postgres:9.6
    restart: "on-failure"
    ports:
      - "5432:5432" # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ./postgredb:/var/lib/postgresql/data
    env_file: ../../.env.dev

  web:
    container_name: app
    build: ../..
    restart: "always"
    env_file: ../../.env.dev
    volumes:
      - ../..:/code
    command: >
      sh -c "python manage.py migrate &&
             gunicorn app.wsgi:application --bind 0.0.0.0:8000 --reload"
    ports:
      - "8000:8000"
    links:
      - postgres
    depends_on:
      - "postgres"
